server:
  tomcat:
    max-http-form-post-size: 20MB

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/memorybank
    username: ${DB_ID}
    password: ${DB_PW}
    driver-class-name: org.postgresql.Driver
  # -- Redis 설정--
  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis
  #---------------
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  ai:
    openai:
      embedding:
        options:
          model: "text-embedding-3-small"

lemon-squeezy:
  webhook-secret: ${LEMON_SQUEEZY_SECRET}
  api-key: ${LEMON_SQUEEZY_API}

spring.ai.openai.api-key: ${OPENAI_API_KEY}rm -rf .git



logging:
  level:
    org.hibernate.SQL: debug